export { useAverias, useAveria, updateAveriaEstado, assignAveria } from './useAverias'
export { useVehiculos, useVehiculo, updateVehiculo, createVehiculo, deleteVehiculo } from './useVehiculos'
export { useLuminarias, marcarLuminariaReparada, registrarLuminariaPendiente } from './useLuminarias'
export { useInventario, updateCantidadInventario, agregarItemInventario, eliminarItemInventario } from './useInventario'
export { useMedidores } from './useMedidores'
export { useProgramacion, useProgramacionItem, createProgramacion, updateProgramacion, deleteProgramacion, completarProgramacion } from './useProgramacion'
export { useUsuarios, useUsuario, updateUsuario, createUsuario } from './useUsuarios'
export { useStats } from './useStats'
export { useLocalizaciones, updateLocalizacion, createLocalizacion, deleteLocalizacion } from './useLocalizaciones'
export { useMateriales, updateMaterial, createMaterial, deleteMaterial } from './useMateriales'
export { useNetworkStatus } from './useNetworkStatus'
